### ISSUE TITLE
Which kraken database should we use?

### ISSUE THREAD

**Issue by tseemann** [CPTR-ReSeqTB/UVP#9]
I can't find any information in the PDF docs.

The YAML file has ` krakendb: /KRAKEN/customdb`

**Comment by mezewudo** [comment]
Default will be the standard kraken database.

**Comment by d-yarmosh** [comment]
Forgive me if this is a simple question, but Kraken version 0.10 has long been replaced. Is its database accessible somewhere?
I cannot rebuild the database because NCBI's ftp site (that it goes to for sequences) has changed format significantly. If I download sequences and place them in the appropriate library folder to proceed, another error crops up becaues gi numbers have been deprecated some years back as well and no longer are present in fasta headers from NCBI. Kraken2 does not have the same database indexing, so I cannot use a modern Kraken database.
